data/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'data'
urlpatterns = [
	path('', views.HomeView, name='home'),

	path('search/', views.SearchView, name='search'),
	path('search_result/', views.SearchResultView, name='search_result'),	

	path('view/', views.SpareView, name='view'),
	path('view/<int:pk>/', views.SpareView, name='view_pk'),

	path('add/', views.AddSpareView, name='add'),
	path('add/<int:force>/', views.AddSpareView, name='add_force'),

	path('miscellaneous/', views.AddMiscellaneous, name='miscellaneous'),

	path('edit/', views.EditSpareView, name='edit'),
	path('edit/<int:pk>/', views.EditSpareView, name='edit_pk'),

	path('issue_list/', views.IssueListView, name='issuelist'),
	path('issue/', views.IssueSpareView, name='issue'),
	path('issue/<int:pk>/', views.IssueSpareView, name='issue_pk'),

	path('return/', views.ReturnSpareView, name='return'),
	path('return/<int:pk>/', views.ReturnSpareView, name='return_pk'),

	path('survey_list/', views.SurveyListView, name='surveylist'),
	path('survey_details/', views.SurveyDetailsView, name='surveydetails'),
	path('survey_details/<int:pk>/', views.SurveyDetailsView, name='surveydetails_pk'),

	path('survey_bypass/', views.SurveyBypassView, name='surveybypass'),
	path('survey_bypass/<int:pk>/', views.SurveyBypassView, name='surveybypass_pk'),

	path('demand_list/', views.DemandListView, name='demandlist'),
	path('demand_details/', views.DemandDetailsView, name='demanddetails'),
	path('demand_details/<int:pk>/', views.DemandDetailsView, name='demanddetails_pk'),


	path('receive_list/', views.ReceiveListView, name='receivelist'),
	path('receive_details/', views.ReceiveDetailsView, name='receivedetails'),
	path('receive_details/<int:pk>/', views.ReceiveDetailsView, name='receivedetails_pk'),

	path('history/', views.HistoryView, name='history'),
	# path('history/issue/', views.IssueHistoryView, name='history_issue'),

	path('spare_class/', views.GetSpareClass, name='spare_class'),

	path('equipment_class/', views.GetEquipmentClass, name='equipment_class'),
	re_path(r'equipment_class/(?P<spare_class>[\w ]+)/', views.GetEquipmentClass, name='equipment_class_slug'),



	path('about_us/', views.AboutUsView, name='about_us'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

osms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('data.urls', namespace='data')),
]

data/views.py
import json, os, re, sys
from django.core.serializers.json import DjangoJSONEncoder
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Spares, SpareClass, EquipmentClass, Authority, Denomination, Issue, IssueList, Return
from .models import Survey, PostSurvey, Demand, PostDemand, Receive, PostReceive
from users.models import Rank

if ('makemigrations' not in sys.argv and 'migrate' not in sys.argv):
	from .forms import SearchForm, SpareForm, SpareClassForm, EquipmentClassForm, DenominationForm, AuthorityForm
	from .forms import IssueForm, ReturnForm, PostSurveyForm, PostDemandForm, PostReceiveForm, RankForm


# Store the search results as a list
SEARCH_RESULT = None

def resetSearch():
	global SEARCH_RESULT
	SEARCH_RESULT = None


# Remove extra spaces
def removeSpace(x):
	try:
		return re.sub(' +', ' ', x)
	except:
		return x


# Return all spare_class present in the database
def GetSpareClass(request):
	spare_class = list(map(lambda x: x.name, SpareClass.objects.all()))
	spare_class.sort()
	return JsonResponse({'spare_class': spare_class})


# Return equipment_class for the given spare_class
def GetEquipmentClass(request, spare_class=None):
	equipment_class = []
	if (spare_class == 'ALL'):
		equipment_class = EquipmentClass.objects.all()
	elif (spare_class):
		equipment_class = EquipmentClass.objects.filter(spare_class=spare_class)
		if (equipment_class.count()):
			equipment_class = list(set(list(map(lambda x: x.name, equipment_class))))
			equipment_class.sort()
			return JsonResponse({'equipment_class': equipment_class})
		else:
			return JsonResponse({'equipment_class': []})


# Home view
@login_required
def HomeView(request):
	# Render home page
	template = 'data/home.html'
	context = {
		'title': 'OSMS | Home'
		
	}
	return render(request, template, context) 


# Search specific spare based on the search form
def SearchView(request):
	template = 'data/search.html'
	context = {
		'title': 'OSMS | Search',
		'user': request.user,
		'form': SearchForm(),
	}
	return render(request, template, context)


# Render the results from the search spare views
def SearchResultView(request):
	global SEARCH_RESULT
	if (request.method == 'POST'):
		form = SearchForm(request.POST)
		# Validate the form
		if (form.is_valid()):
			# Get the fields from the form
			spare_class = form.cleaned_data.get('spare_class')
			equipment_class = form.cleaned_data.get('equipment_class')
			pattern_number = form.cleaned_data.get('pattern_number')
			description = form.cleaned_data.get('description')
			
			# Filter the spares
			spares = Spares.objects.filter()
			if (spare_class != 'ALL'):
				spares = spares.filter(spare_class=spare_class)
			if (equipment_class != 'ALL'):
				spares = spares.filter(equipment_class=equipment_class)
			if (pattern_number):
				spares = spares.filter(pattern_number__icontains=pattern_number)
			if (description):
				spares = spares.filter(description__icontains=description)
			
			# No such spare found
			if (spares.count() == 0):
				resetSearch()
				messages.info(request, "No matching spare found!")
				return redirect('data:search')
			
			# Spares matching the description found
			else:
				SEARCH_RESULT = [e.pk for e in list(spares)]
				template = 'data/searchlist.html'
				context = {
					'title': 'OSMS | Search Result',
					'user': request.user,
					'spares': spares,
				}
				return render(request, template, context)
		# Form validation failed
		else:
			resetSearch()
			messages.error(request, "Form validation failed!")
			return redirect('data:search')

	# Handle get requests  - IF USING BACK BUTTON 
	elif (request.method == 'GET'):
		# If spares already exists
		if (SEARCH_RESULT):
			spares = Spares.objects.filter(pk__in=SEARCH_RESULT)
			template = 'data/searchlist.html'
			context = {
				'title': 'OSMS | Result',
				'user': request.user,
				'spares': spares,
			}
			return render(request, template, context)
		else:
			return redirect('data:search')
		

# Display the spare with given pk
def SpareView(request, pk=None):
	if (pk):
		# Search for the spare that matches the given pk
		spare = Spares.objects.filter(pk=pk)
		if (spare.count() != 0):
			spare = spare[0]
			
			# Figure out the next and previous spares using SEARCH_RESULT
			next_spare = previous_spare = -1
			if (SEARCH_RESULT):
				if (pk in SEARCH_RESULT):
					length = len(SEARCH_RESULT)
					index = SEARCH_RESULT.index(pk)
					
					# Figure out the next spare
					if (index + 1 < length):
						next_spare = SEARCH_RESULT[index + 1]
					else:
						next_spare = SEARCH_RESULT[0]
					
					# Figure out the previous spare
					if (index > 0):
						previous_spare = SEARCH_RESULT[index - 1]
					else:
						previous_spare = SEARCH_RESULT[length - 1]

			# Found the spare, redirect to spare view page
			template = 'data/searchdetails.html'
			context = {
				'title': 'OSMS | View',
				'user': request.user,
				'spare': spare,
				'form': SpareForm(),
				'next': next_spare,
				'previous': previous_spare,
			}
			return render(request, template, context)
		else:
			messages.info(request, 'No matching spare found!')
			return redirect('data:search')
	
	# No pk value specified
	else:
		return redirect('data:search')


# Add a new spare
def AddSpareView(request, force=False):
	global SEARCH_RESULT
	if (request.method == 'POST'):
		form = SpareForm(request.POST, request.FILES)
		# Check if the form is valid
		if (form.is_valid()):
			# Filter the spares
			spare_class = form.cleaned_data.get('spare_class')
			equipment_class = form.cleaned_data.get('equipment_class')
			pattern_number = form.cleaned_data.get('pattern_number')
			spares = Spares.objects.filter(spare_class=spare_class, equipment_class=equipment_class)
			
			# Check if the pattern number matches exactly
			spare = spares.filter(pattern_number=pattern_number)
			if (spare.count() != 0):
				messages.info(request, "Spare already exists!")
				return redirect('data:edit_pk', pk=spare[0].pk)
			else:
				form.save()
				messages.success(request, "Spare added successfully!")
		# Form validation failed
		else:
			messages.error(request, "Form validation failed!")
			return redirect('data:add')
	
	template = 'data/add.html'
	context = {
		'title': 'OSMS | Add',
		'user': request.user,
		'form': SpareForm(),
	}
	return render(request, template, context)


# Edit an existing spare
def EditSpareView(request, pk=None):
	if (pk):
		# Search for the spare that matches the given pk
		spare = Spares.objects.filter(pk=pk)
		if (spare.count() != 0):
			spare = spare[0]
			if (request.method == 'POST'):
				form = SpareForm(request.POST, request.FILES, instance=spare)
				if (form.is_valid()):
					# Save the edited details
					form.save()
					messages.success(request, "Spare details updated!")
					return redirect('data:view_pk', pk=pk)
				else:
					messages.error(request, "Form validation failed!")
					return redirect('data:edit_pk', pk=pk)

			# Render the spare edit page
			template = 'data/edit.html'
			context = {
				'title': 'OSMS | Edit',
				'spare': spare,
				'form': SpareForm(instance=spare),
			}
			return render(request, template, context)
		else:
			messages.info(request, 'No matching spare found!')
			return redirect('data:search')
	# No pk value specified
	else:
		return redirect('data:home')


# List of the spares issued
def IssueListView(request):
	entries = IssueList.objects.all()
	template = 'data/issuelist.html'
	context = {
		'title': 'OSMS | Issue List',
		'entries': entries, 
	}
	return render(request, template, context)


# Issue the spare to a user
def IssueSpareView(request, pk=None):
	if (pk):
		form = IssueForm()
		# Get the spare with the given pk
		spare = Spares.objects.filter(pk=pk)		
		if (spare.count() != 0):
			spare = spare[0]	
			
			if (request.method == 'POST'):
				form = IssueForm(request.POST)
				if (form.is_valid()):
					quantity_issued = form.cleaned_data['quantity_issued']
					username = form.cleaned_data['username']
					if (quantity_issued == 0):
						messages.error(request, "Issued quantity must be greater than 0!")
					elif (quantity_issued > spare.quantity_available):
						messages.error(request, "Issued quantity more than available quantity!")
					else:
						form = form.save(commit=False)
						form.spare = spare
						form.save()   #this saves Issue model instance						
						spare.quantity_available -= quantity_issued
						spare.save()
						# Modify the issue list table ie creating temprory entry
						issue = Issue.objects.filter(spare=pk)
						issue = issue[0]
						spare_toreturn = IssueList.objects.filter(issue_entry=issue)
						
						if (spare_toreturn.count() == 0):
							IssueList.objects.create(issue_entry=form, quantity_toreturn=quantity_issued)
						else:
							spare_toreturn = spare_toreturn[0]
							spare_toreturn.quantity_toreturn += quantity_issued
							spare_toreturn.save()

						# Add to survey / demand based on spare category
						if (spare.category == 'CONSUMABLE'):
							# Check if the spare exists in the demand table
							demand_entry = Demand.objects.filter(spare=spare)
							if (demand_entry.count() == 0):
								# Create a new demand entry
								Demand.objects.create(spare=spare, quantity_todemand=quantity_issued)
							else:
								demand_entry = demand_entry[0]
								demand_entry.quantity_todemand += quantity_issued
								demand_entry.save()
						else:
							# Check if the spare exists in the survey table
							survey_entry = Survey.objects.filter(spare=spare)
							if (survey_entry.count() == 0):
								# Create a new survey entry
								Survey.objects.create(spare=spare, quantity_tosurvey=quantity_issued)
							else:
								survey_entry = survey_entry[0]
								survey_entry.quantity_tosurvey += quantity_issued
								survey_entry.save()

data/templates/data/demandlist.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
{% endblock pagestyles %}

{% block headerpageplugins %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS -->
{% endblock headerpageplugins %}
{% block newplugins %}
<link href="{% static 'data/css/demandlist.css' %}" rel="stylesheet" type="text/css" />
{% endblock newplugins %}
{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green">
                            <i class="icon-list font-green"></i>
                            <span class="caption-subject bold uppercase" id="table_head">Results</span>
                        </div>
                        <div class="tools"> </div>
                    </div>

                    <div class="portlet-body">
                      <table class="table table-striped table-bordered table-hover table-header-fixed" id="sample_1">
                        <thead>
                            <tr class = "table-columns">
                                <th class="none">PK</th>
                                <th class="all">Pattern Number</th>
                                <th class="min-phone-l">Class of Spare</th>
                                <th class="min-tablet">Class of Equipment</th>
                                <th class="none">Spare Description</th>
                                <th class="none">Quantity To Demand</th>
                                <th class="min-tablet">Survey Number</th>
                                <th class="min-tablet">Survey Remarks</th>
                            </tr>
                        </thead>
                        <tbody id="table_body"></tbody>
                      </table>


                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->
{% endblock content %}

{% block footerpageplugins %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{% static 'assets/global/scripts/datatable.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/datatables.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script>
     // URL to return page
    var url_demand = "{% url 'data:demanddetails' %}";
    // Load the spares into a variable
    let result = [
    {% for entry in entries %}
        {% with spare=entry.spare %}    
          {% if not forloop.first %}, {% endif %}
          {
            pk: '{{ entry.pk }}',
            pattern_number: '{{ spare.pattern_number }}',
            spare_class: '{{ spare.spare_class }}',
            equipment_class: '{{ spare.equipment_class }}',            
            description: '{{ spare.description }}',
            category: '{{ spare.category }}',
            critical: '{{ spare.critical }}',
            quantity_todemand: '{{ entry.quantity_todemand }}',
            survey_number:'{{ entry.survey_entry.survey_number }}',
            survey_remarks:'{{entry.survey_entry.remarks}}',
          }
        {% endwith %}
        {% endfor %}
    ];
</script>

<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>
<script src="{% static 'data/js/demandlist.js' %}" type="text/javascript"></script>
<script>
  LoadTable(true);
</script>
<!-- END PAGE LEVEL SCRIPTS -->
{% endblock pagescripts %}

data/templates/data/search.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
{% endblock pagestyles %}

{% block headerpageplugins %}
<link href="{% static 'assets/global/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'assets/global/plugins/select2/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'assets/layouts/layout5/css/layout.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock headerpageplugins %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green">
                            <i class="icon-magnifier font-green"></i>
                            <span class="caption-subject bold uppercase">Search</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn btn-sm default" id="button_cancel">Cancel</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-sm green" id="button_search">Search</a>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form role="form" id="form_search" method="POST" action="{% url 'data:search_result' %}">
                            {% csrf_token %}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.spare_class }}
                                            <label class="form_control_1">{{ form.spare_class.label }}</label>
                                            <span class="help-block">Select the spare type...</span>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-4">                                        
                                        <div class="form-group form-md-line-input form-md-floating-label">                                            
                                            {{ form.equipment_class }}
                                            <label class="form_control_1">{{ form.equipment_class.label }}</label>
                                            <span class="help-block">Select the spare class...</span>
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.pattern_number }}
                                            <label class="form_control_1">{{ form.pattern_number.label }}</label>
                                            <span class="help-block">Enter the pattern number of the spare...</span>
                                        </div>
                                    </div>
                                    <br><br><br><br>
                                    <div class="col-md-12">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.description }}
                                            <label class="form_control_1">{{ form.description.label }}</label>
                                            <span class="help-block">Description about the spare...</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
                <!-- END SAMPLE FORM PORTLET-->
            </div>
        </div>
{% endblock content %}

{% block footerpageplugins %}
{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script>
    var url_getEquipmentClass = "{% url 'data:equipment_class' %}"; 
</script>
<script src="{% static 'data/js/search.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/select2/js/select2.full.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/components-select2.min.js' %}" type="text/javascript"></script>
                <!-- END PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL SCRIPTS -->
{% endblock pagescripts %}

data/templates/data/searchdetails.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="{% static '/assets/pages/css/blog.min.css' %}" rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL STYLES -->
{% endblock pagestyles %}

{% block headerpageplugins %}
{% endblock headerpageplugins %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
  <!-- BEGIN CONTENT BODY -->
  <div class="page-content">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
          <div class="portlet-title">
            <div class="caption font-green">
              <i class="icon-settings font-green"></i>
              <span class="caption-subject bold uppercase">Spare Specific Details</span>
            </div>
            <div class="actions">
              <div class="btn-group">
                <a class="btn btn-sm default" href="{% url 'data:search_result' %}" style="margin-right: 2px;">Back</a>
              </div>
              {% if user.can_edit %}
              <div class="btn-group">
                <a class="btn btn-sm red" href="{% url 'data:edit' %}{{ spare.pk }}">Edit</a>
              </div>
              {% endif %}
              <div class="btn-group">
                <a id = "button_issue" class="btn btn-sm green a_issue" role="button" href="{% url 'data:issue' %}{{ spare.pk }}">Issue</a>
              </div>
            </div>
          </div>

          <div class="portlet-body form">
            <form role="form">
              {% csrf_token %}
              <div class="form-body">

                <div class="row">
                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.spare_class.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.spare_class }}">
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.equipment_class.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.equipment_class }}">
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.pattern_number.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.pattern_number }}">
                    </div>
                  </div>

                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.description.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.description }}">
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.compartment.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.compartment }}">
                    </div>
                  </div>
                  <div class="col-md-4 col-sm-4 form-group">
                    <label class="control-label">{{ form.location.label }}</label>
                    <div>
                      <input type="text" class="form-control" value="{{ spare.location }}">
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class=" col-md-6 col-sm-6">
                    <div class="row">
                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.denomination.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.denomination }}">
                        </div>
                      </div>
                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.quantity_authorised.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.quantity_authorised }}">
                        </div>
                      </div>
                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.quantity_available.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.quantity_available }}">
                        </div>
                      </div>


                      <div class="col-md-6 col-sm-6 form-group">
                        <label class="control-label">{{ form.category.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.category }}">
                        </div>
                      </div>
                      <div class="col-md-6 col-sm-6 form-group">
                        <label class="control-label">{{ form.critical.label }}</label>
                        <div>
                          {% if spare.critical %}
                          <input type="text" class="form-control" value="YES">
                          {% else %}
                          <input type="text" class="form-control" value="NO">
                          {% endif %}
                        </div>
                      </div>



                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.authority.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.authority }}">
                        </div>
                      </div>
                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.page.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.page }}">
                        </div>
                      </div>
                      <div class="col-md-4 col-sm-4 form-group">
                        <label class="control-label">{{ form.line.label }}</label>
                        <div>
                          <input type="text" class="form-control" value="{{ spare.line }}">
                        </div>
                      </div>

                      <div class="col-md-12 col-sm-12 form-group">
                        <label class="control-label">{{ form.remarks.label }}</label>
                        <div>
                          <textarea class="form-control textarea" rows="5">{{ spare.remarks }}</textarea>
                        </div>

                      </div>
                    </div>
                    
                  </div>


                  <div class="col-md-6 col-sm-6" style="padding-top: 22px;">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                      {% if spare.image %}
                      <div class="fileinput-new thumbnail" style=" height: 350px;">
                        <img id="img_spare" src="{{ spare.image.url }}" style="width: 100%; height: 100%;">
                      </div>
                      {% else %}
                      <div class="fileinput-new thumbnail" style=" height: 350px;">
                        <img src="{% static 'assets/myassets/img/imagenotloaded.png' %}" alt=""
                          style="width: 100%; height: 100%;" />
                      </div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>

              <hr>

              <div class="portlet-body form">
                <div class="row">
                  <div class="col-md-6 col-sm-6">
                    {% if previous != -1 %}
                    <a id = "button_left" class="btn btn-sm green a_left" role="button" href="{% url 'data:view' %}{{ previous }}/">Previous</a>
                    {% endif %}
                  </div>
                  <div class="col-md-6 col-sm-6" align="right">
                    {% if next != -1 %}
                    <a id = "button_right" class="btn btn-sm green a_right" role="button" href="{% url 'data:view' %}{{ next }}/">Next</a>
                    {% endif %}
                  </div>
                </div>
              </div>

            </form>
          </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block footerpageplugins %}
{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>
<script src="{% static 'data/js/view.js' %}" type="text/javascript"></script>

<!-- END PAGE LEVEL SCRIPTS -->
{% endblock pagescripts %}