data/urls.py
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'data'
urlpatterns = [
	path('', views.HomeView, name='home'),

	path('search/', views.SearchView, name='search'),
	path('search_result/', views.SearchResultView, name='search_result'),	

	path('view/', views.SpareView, name='view'),
	path('view/<int:pk>/', views.SpareView, name='view_pk'),

	path('add/', views.AddSpareView, name='add'),
	path('add/<int:force>/', views.AddSpareView, name='add_force'),

	path('miscellaneous/', views.AddMiscellaneous, name='miscellaneous'),

	path('edit/', views.EditSpareView, name='edit'),
	path('edit/<int:pk>/', views.EditSpareView, name='edit_pk'),

	path('issue_list/', views.IssueListView, name='issuelist'),
	path('issue/', views.IssueSpareView, name='issue'),
	path('issue/<int:pk>/', views.IssueSpareView, name='issue_pk'),

	path('return/', views.ReturnSpareView, name='return'),
	path('return/<int:pk>/', views.ReturnSpareView, name='return_pk'),

	path('survey_list/', views.SurveyListView, name='surveylist'),
	path('survey_details/', views.SurveyDetailsView, name='surveydetails'),
	path('survey_details/<int:pk>/', views.SurveyDetailsView, name='surveydetails_pk'),

	path('survey_bypass/', views.SurveyBypassView, name='surveybypass'),
	path('survey_bypass/<int:pk>/', views.SurveyBypassView, name='surveybypass_pk'),

	path('demand_list/', views.DemandListView, name='demandlist'),
	path('demand_details/', views.DemandDetailsView, name='demanddetails'),
	path('demand_details/<int:pk>/', views.DemandDetailsView, name='demanddetails_pk'),


	path('receive_list/', views.ReceiveListView, name='receivelist'),
	path('receive_details/', views.ReceiveDetailsView, name='receivedetails'),
	path('receive_details/<int:pk>/', views.ReceiveDetailsView, name='receivedetails_pk'),

	path('history/', views.HistoryView, name='history'),
	# path('history/issue/', views.IssueHistoryView, name='history_issue'),

	path('spare_class/', views.GetSpareClass, name='spare_class'),

	path('equipment_class/', views.GetEquipmentClass, name='equipment_class'),
	re_path(r'equipment_class/(?P<spare_class>[\w ]+)/', views.GetEquipmentClass, name='equipment_class_slug'),



	path('about_us/', views.AboutUsView, name='about_us'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

osms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('data.urls', namespace='data')),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	path('signup/', views.CustomUserSignupView, name='custom_user_signup'),
	path('profile/edit/', views.EditProfileView, name='editprofile'),	
	path('manage/', views.ManageUserView, name='manage_users'),	
	path('lock-screen/', views.LockScreenView, name ='lockscreen'),
	path('profile/', views.CustomUserProfileCreationView, name='custom_user_profile'),
	path('login/', views.LoginView, name='login'),
	path('logout/', views.LogoutView, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.utils.timezone import now
from .managers import CustomUserManager

class Department(models.Model):
	# populated by default using excel_todb.py
	name = models.CharField(max_length=50, unique=True)

class Rank(models.Model):
	# populated by default using excel_todb.py
	name = models.CharField(max_length=100,  unique=True)

class CustomUserProfile(models.Model):
	rank = models.ForeignKey(Rank, on_delete=models.PROTECT)
	firstname = models.SlugField(max_length=50, default='')
	lastname = models.SlugField(max_length=50, blank=True, default='')	
	personal_number = models.SlugField(max_length=15, unique=True, default='')
	section = models.CharField(max_length=50, blank=True, default='')
	ship_joining_date = models.DateTimeField(default=now,null=True)
	ship_leaving_date = models.DateTimeField(null=True)
	remarks = models.CharField(max_length=200, default='')
	access_level_choices = [
		# first letter goes into the database , and second letter is for forms.py to show
		('0', 'ENGSUPERUSER'),
		('1','SUPERUSER'),   
		('2','STOREKEEPER'),
		('3','OTHERS')
	]
	access_level = models.CharField(max_length=20, default='2',null=True, choices=access_level_choices)
	department = models.ForeignKey(Department, on_delete=models.PROTECT)
	user_active = models.BooleanField(default=True)

class CustomUser(AbstractBaseUser):	
	username = models.CharField(max_length=100, unique=True)
	user_profile = models.ForeignKey(CustomUserProfile ,on_delete=models.PROTECT)
	is_active = models.BooleanField(default=True)
	is_admin = models.BooleanField(default=False)

	objects = CustomUserManager()	

	REQUIRED_FIELDS = ['user_profile']
	USERNAME_FIELD = 'username'

	def __str__(self):
		return self.username

	def has_perm(self, perm, object=None):
		return True

	def has_module_perms(self, app_label):
		return True

	@property
	def is_staff(self):
		return self.is_admin

users/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse

from .models import CustomUser, CustomUserProfile, Rank, Department
from .forms import CustomUserCreationForm, CreateProfileForm, EditProfileForm , LoginForm ,ChangePasswordForm, ManageUserForm


def LoginView(request):
	form = LoginForm()
	if (request.method == 'POST'):
		username = request.POST['username']
		password = request.POST['password']
		department = request.POST['department']
		user_entry = CustomUser.objects.filter(username=username)
		if user_entry.count() != 0:
			user_entry = user_entry[0]
			user_department = user_entry.user_profile.department.id
			if (str(user_department) == str(department) and user_entry.profile.user_active == True):
				user = authenticate(username=username, password=password)
				if user is not None:
					login(request, user)
					# Redirect to home
					return redirect('data:home')
				else:
					# Return an 'invalid login' error message.
					messages.error(request, "Invalid login credentials!")
			else:
				messages.error(request, "Invalid login credentials!")
		else:
			messages.error(request, "No user found!")

	template = 'users/login.html'	
	context = {
		'title': 'OSMS | User Login',
		'form': form,		
	}
	return render(request, template, context)


@login_required
def LogoutView(request):
	logout(request)
	return redirect('users:login') 


@login_required
def CustomUserSignupView(request):
	form = CustomUserCreationForm()
	if (request.method == 'POST'):
		form = CustomUserCreationForm(request.POST)
		if (form.is_valid()):
			username = form.cleaned_data['username']
			customuser_entry = CustomUser.objects.filter(username=username)	
			userprofile_entry = CustomUserProfile.objects.filter(personal_number=username)

			# Check if user already exists
			if (customuser_entry.count() != 0):
				messages.error(request, "User already exists!")
			# Check if profile corresponding to the personal_number exists
			elif (userprofile_entry.count() == 0):
				messages.error(request, "Profile corresponding to the user does not exist!")
			# Create user
			else:
				userprofile_entry = userprofile_entry[0]
				form = form.save(commit=False)
				form.user_profile = userprofile_entry
				form.save()
				messages.success(request, "User created successfully!")
		else:
			messages.error(request, "Form validation failed!")
	
	template = 'users/signup.html'
	context = {
		'title': 'O-SMS | Login User Signup-Form',
		'form': form,
		'user': request.user,
	}
	return render(request, template, context)


def CustomUserProfileCreationView(request):
	form = CreateProfileForm()
	if (request.method == 'POST'):
		form = CreateProfileForm(request.POST)
		if (form.is_valid()):
			personal_number = form.cleaned_data['personal_number'].upper()
			customuserprofile_entry = CustomUserProfile.objects.filter(personal_number=personal_number)
			if (customuserprofile_entry.count() != 0 ):
				customuserprofile_entry = customuserprofile_entry[0]
				messages.error(request, "Profile with this personal number already exists!")
				return redirect('users:custom_user_profile')
			else: 
				form.save()
				messages.success(request, "New user profile having personal number " + personal_number + " created!")
				return redirect('users:custom_user_profile')
		else:
			messages.error(request, "Form validation failed!")
	
	template = 'users/createprofile.html'
	context = {
		'title': 'O-SMS | Profile Creation Form',
		'form': form,
		'user': request.user,
	}
	return render(request, template, context)	

@login_required
def EditProfileView(request):
	# Fetch the profile of the currently logged in user
	username = request.user.username
	profile = CustomUserProfile.objects.filter(personal_number=username)	
	if (profile.count() != 0):
		profile = profile[0]
		profile.ship_joining_date = datetime.strftime(profile.ship_joining_date, '%d %B %Y - %H:%M')
		if (request.method == 'POST'):
			form_id = request.POST.get('form_id')

			# Process based on the form_id received
			if (form_id == '1'):
				# Change profile details
				form1 = EditProfileForm(request.POST, instance=profile)	
				if (form1.is_valid()):
					personal_number = form1.cleaned_data['personal_number']
					form1.save()
					# Change the username if personal number changes
					if (personal_number != username):
						user = CustomUser.objects.get(username=username)
						user.username = personal_number
						user.save()
					messages.success(request, "User profile updated!")
				else:
					messages.error(request, "Form validation failed!")
				
			elif (form_id == '2'):
				# Change password
				form2 = ChangePasswordForm(request.POST)
				if (form2.is_valid()):
					old_password = form2.cleaned_data['old_password']
					password1 = form2.cleaned_data['password1']
					password2 = form2.cleaned_data['password2']
					user = authenticate(username=username, password=old_password)
					if (user and password1 != '' and password1 == password2):
						form2.save(user)
						messages.success(request, "Password changed successfully!")
						return redirect('users:logout')
					else:
						messages.error(request, "Invalid credentials!")
				else:
					messages.error(request, "Form validation failed!")
			return redirect('users:editprofile')

		# Render the spare edit page
		template = 'users/edit_profile.html'
		context = {
			'title': 'OSMS | My Profile',
			'user': request.user,
			'form1': EditProfileForm(instance=profile),
			'form2': ChangePasswordForm
		}
		return render(request, template, context)
	else:
		messages.info(request, 'No profile  details found!')
		return redirect('data:home')


@login_required
def LockScreenView(request):
	context = {
		'title': 'OSMS | Lock Screen',
	}
	template = 'users/lock-screen.html'
	return render(request, template, context)
	
@login_required
def ManageUserView(request):
	form = ManageUserForm()
	if (request.method == 'POST'):
		form = ManageUserForm(request.POST)
		if (form.is_valid()):
			password = form.cleaned_data['password']
			username = request.user.username
			# Validate the user
			user = authenticate(username=username, password=password)
			if (user is not None):
				form_id = request.POST.get('form_id')
				user_id = form.cleaned_data['username']
				userprofile = CustomUserProfile.objects.get(id=user_id)	
				# Change access level if form id is 1
				if (form_id == '1'):
					userprofile.access_level = form.cleaned_data['access_level']
					userprofile.save()
					messages.success(request, 'User access level changed!')
				# Delete user if form id is 2
				elif (form_id == '2'):
					userprofile.user_active = False
					userprofile.save()
					user = CustomUser.objects.filter(username=userprofile.personal_number)
					if (user.count() != 0):
						user[0].delete()
					messages.success(request, 'User deleted!')
			# Invalid user credentials
			else:
				messages.error(request, 'Invalid credentials!')
		else:
			messages.error(request, "Form validation failed!")
	
	template = 'users/manage_users.html'
	context = {
		'title': 'O-SMS | Manage Users',
		'form': form,
		'user': request.user,
	}
	return render(request, template, context)	

users/templates/users/loginuser_creation.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
{% endblock pagestyles %}

{% block headerpageplugins %}
<link href="{% static 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css' %}" rel="stylesheet"
    type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}"
    rel="stylesheet" type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet"
    type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}"
    rel="stylesheet" type="text/css" />

{% endblock headerpageplugins %}
{% block newplugins %}
<link href="{% static 'users/css/super_signup.css' %}" rel="stylesheet" type="text/css" />
{% endblock newplugins %}
{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">          
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green">
                            <i class="icon-settings font-green"></i>
                            <span class="caption-subject bold uppercase">Add Login User</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn btn-sm red cancelbutton" id="button_cancel">Cancel</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-sm green" id="button_user_save">Save</a>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form role="form" id="form_signupuser" method="POST"
                            action="{% url 'users:custom_user_signup' %}">
                            {% csrf_token %}
                            <div class="form-body">
                                <div class="row">

                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.department}}
                                            <label class="form_control_1">{{ form.department.label }}</label>
                                            <span class="help-block">Enter your section in department...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.username }}
                                            <label class="form_control_1">{{ form.username.label }}</label>
                                            <span class="help-block">If username not in the list create user profile first...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.access_level }}
                                            <label class="form_control_1">{{ form.access_level.label }}</label>
                                            <span class="help-block">Select desired user option...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <br><br>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.password1 }}
                                            <label class="form_control_1">{{ form.password1.label }}</label>
                                            <span class="help-block">Enter your password...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.password2 }}
                                            <label class="form_control_1">{{ form.password2.label }}</label>
                                            <span class="help-block">Re-enter your password...</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
</div>



{% endblock content %}

{% block footerpageplugins %}
<script src="{% static 'assets/global/plugins/moment.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"
    type="text/javascript"></script>
{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/components-date-time-pickers.min.js' %}" type="text/javascript"></script>
<script src="{% static 'users/js/user_creation.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

{% endblock pagescripts %}

users/templates/users/manage_users.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
{% endblock pagestyles %}

{% block headerpageplugins %}

{% endblock headerpageplugins %}
{% block newplugins %}
<link href="{% static 'users/css/manage_users.css' %}" rel="stylesheet" type="text/css" />
{% endblock newplugins %}
{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">          
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green">
                            <i class="icon-settings font-green"></i>
                            <span class="caption-subject bold uppercase">Add Login User</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn btn-sm red cancelbutton" id="button_cancel">Cancel</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-sm green" id="button_changeaccess">Change Access Level</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-sm green" id="button_delete">Delete Username</a>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form role="form" id="form_manageusers" method="POST"
                            action="{% url 'users:manage_users' %}">
                            {% csrf_token %}
                            <input type="text" id="input_hidden" name="form_id" hidden>

                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.username }}
                                            <label class="form_control_1">{{ form.username.label }}</label>
                                            <span class="help-block">If username not in the list create user profile first...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.access_level }}
                                            <label class="form_control_1">{{ form.access_level.label }}</label>
                                            <span class="help-block">Select desired access level to change...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label" id="div_password">
                                            {{ form.password }}
                                            <label class="form_control_1">{{ form.password.label }}</label>
                                            <span class="help-block">Enter login password to authenticate...</span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
</div>



{% endblock content %}

{% block footerpageplugins %}

{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>

<script src="{% static 'users/js/manage_users.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

{% endblock pagescripts %}

users/templates/users/signup.html
{% extends 'data/base.html' %}
{% load static %}

{% block pagestyles %}
{% endblock pagestyles %}

{% block headerpageplugins %}
<link href="{% static 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css' %}" rel="stylesheet"
    type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}"
    rel="stylesheet" type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css' %}" rel="stylesheet"
    type="text/css" />
<link href="{% static 'assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}"
    rel="stylesheet" type="text/css" />

{% endblock headerpageplugins %}
{% block newplugins %}
<link href="{% static 'users/css/super_signup.css' %}" rel="stylesheet" type="text/css" />
{% endblock newplugins %}
{% block content %}
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">          
                <!-- BEGIN SAMPLE FORM PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-green">
                            <i class="icon-settings font-green"></i>
                            <span class="caption-subject bold uppercase">Add Login User</span>
                        </div>
                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn btn-sm red cancelbutton" id="button_cancel">Cancel</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-sm green" id="button_user_save">Save</a>
                            </div>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form role="form" id="form_signupuser" method="POST"
                            action="{% url 'users:custom_user_signup' %}">
                            {% csrf_token %}
                            <div class="form-body">
                                <div class="row">

                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.department}}
                                            <label class="form_control_1">{{ form.department.label }}</label>
                                            <span class="help-block">Enter your section in department...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.username }}
                                            <label class="form_control_1">{{ form.username.label }}</label>
                                            <span class="help-block">If username not in the list create user profile first...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input ">
                                            {{ form.access_level }}
                                            <label class="form_control_1">{{ form.access_level.label }}</label>
                                            <span class="help-block">Select desired user option...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <br><br>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.password1 }}
                                            <label class="form_control_1">{{ form.password1.label }}</label>
                                            <span class="help-block">Enter your password...</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group form-md-line-input form-md-floating-label">
                                            {{ form.password2 }}
                                            <label class="form_control_1">{{ form.password2.label }}</label>
                                            <span class="help-block">Re-enter your password...</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
        </div>
    </div>
</div>



{% endblock content %}

{% block footerpageplugins %}
<script src="{% static 'assets/global/plugins/moment.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}"
    type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"
    type="text/javascript"></script>
{% endblock footerpageplugins %}

{% block pagescripts %}
<!-- BEGIN PAGE LEVEL SCRIPTS -->

<script src="{% static 'assets/pages/scripts/form-samples.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/pages/scripts/components-date-time-pickers.min.js' %}" type="text/javascript"></script>
<script src="{% static 'users/js/signup.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->

{% endblock pagescripts %}